Le login est fonctionnel
SpaceLock/spacelock pull request #40
Opened 2023-01-21 16:41 UTC by Fiyorden

2023-01-21 16:51 UTC, matrox471 requested changes
doit utilisez les bonnes tables

2023-01-21 17:42 UTC, Vetal01 commented
Il utilise déja la table customer à la place de user pour le login

2023-01-22 15:55 UTC, matrox471 commented
Je ne peux pas valider ton fichier 'welcome.blade.php' parce qu'il n'est pas a jour avec celui de la branche main. Ce n'est pas grave, Garde ton code, faudra mettre a jour le compo de la nav général et pas juste de welcome.

2023-01-22 15:58 UTC, matrox471 approved these changes

2023-01-22 15:59 UTC, merged

2023-01-22 16:27 UTC, Vetal01 commented
Oui j'avais gardé la vue d'accueil de laravel pour tester. Il suffit de mettre le bouton + la route dans la nav pour que ce soit bon pour le projet